PACKET_TAGS = {
    0: "Reserved",
    1: "Public-Key Encrypted Session Key Packet",
    2: "Signature Packet",
    3: "Symmetric-Key Encrypted Session Key Packet",
    4: "One-Pass Signature Packet",
    5: "Secret Key Packet",
    6: "Public Key Packet",
    7: "Secret Subkey Packet",
    8: "Compressed Data Packet",
    9: "Symmetrically Encrypted Data Packet",
    10: "Marker Packet",
    11: "Literal Data Packet",
    12: "Trust Packet",
    13: "User ID Packet",
    14: "Public Subkey Packet",
    17: "User Attribute Packet",
    18: "Sym. Encrypted and Integrity Protected Data Packet",
    19: "Modification Detection Code Packet",
    60: "Private or Experimental Values",
    61: "Private or Experimental Values",
    62: "Private or Experimental Values",
    63: "Private or Experimental Values"
}

LENGTH_TYPE = [
    "One-octet length",
    "Two-octet length",
    "Four-octet length",
    "Indeterminate length"
]

SIGNATURE_TYPE = {
    b'\x00': "Signature of a binary document",
    b'\x01': "Signature of a canonical text document",
    b'\x02': "Standalone signature",
    b'\x10': "Generic certification of a User ID and Public-Key packet",
    b'\x11': "Persona certification of a User ID and Public-Key packet",
    b'\x12': "Casual certification of a User ID and Public-Key packet",
    b'\x13': "Positive certification of a User ID and Public-Key packet",
    b'\x18': "Subkey Binding Signature",
    b'\x19': "Primary Key Binding Signature",
    b'\x1f': "Signature directly on a key",
    b'\x20': "Key revocation signature",
    b'\x28': "Subkey revocation signature",
    b'\x30': "Certification revocation signature",
    b'\x40': "Timestamp signature",
    b'\x50': "Third-Party Confirmation signature"
}

SUBPACKET_TYPE = [
    "Reserved",
    "Reserved",
    "Signature Creation Time",
    "Signature Expiration Time",
    "Exportable Certification",
    "Trust Signature",
    "Regular Expression",
    "Revocable",
    "Reserved",
    "Key Expiration Time",
    "Placeholder for backward compatibility",
    "Preferred Symmetric Algorithms",
    "Revocation Key",
    "Reserved",
    "Reserved",
    "Reserved",
    "Issuer",
    "Reserved",
    "Reserved",
    "Reserved",
    "Notation Data",
    "Preferred Hash Algorithms",
    "Preferred Compression Algorithms",
    "Key Server Preferences",
    "Preferred Key Server",
    "Primary User ID",
    "Policy URL",
    "Key Flags",
    "Signer's User ID",
    "Reason for Revocation",
    "Features",
    "Signature Target",
    "Embedded Signature",

]

PUBLIC_KEY_ALGORITHMS = {
    1: "RSA (Encrypt or Sign)",
    2: "RSA Encrypt-Only",
    3: "RSA Sign-Only",
    16: "Elgamal (Encrypt-Only)",
    17: "DSA (Digital Signature Algorithm)",
    18: "Elliptic Curve",
    19: "ECDSA",
    20: "Formerly Elgamal Encrypt or Sign",
    21: "Diffie-Hellman",
    100: "Reserved for Private/Experimental Use",
    101: "Reserved for Private/Experimental Use",
    102: "Reserved for Private/Experimental Use",
    103: "Reserved for Private/Experimental Use",
    104: "Reserved for Private/Experimental Use",
    105: "Reserved for Private/Experimental Use",
    106: "Reserved for Private/Experimental Use",
    107: "Reserved for Private/Experimental Use",
    108: "Reserved for Private/Experimental Use",
    109: "Reserved for Private/Experimental Use",
    110: "Reserved for Private/Experimental Use",
}

HASH_ALGORITHMS = {
    1: "MD5",
    2: "SHA-1",
    3: "RIPEMD-160",
    4: "Reserved",
    5: "Reserved",
    6: "Reserved",
    7: "Reserved",
    8: "SHA-256",
    9: "SHA-384",
    10: "SHA-512",
    11: "SHA-224",
    100: "Reserved for Private/Experimental Use",
    101: "Reserved for Private/Experimental Use",
    102: "Reserved for Private/Experimental Use",
    103: "Reserved for Private/Experimental Use",
    104: "Reserved for Private/Experimental Use",
    105: "Reserved for Private/Experimental Use",
    106: "Reserved for Private/Experimental Use",
    107: "Reserved for Private/Experimental Use",
    108: "Reserved for Private/Experimental Use",
    109: "Reserved for Private/Experimental Use",
    110: "Reserved for Private/Experimental Use",
}

COMPRESSION_ALGORITHMS = {
    0: "Uncompressed",
    1: "ZIP",
    2: "ZLIB",
    3: "BZip2",
    100: "Reserved for Private/Experimental Use",
    101: "Reserved for Private/Experimental Use",
    102: "Reserved for Private/Experimental Use",
    103: "Reserved for Private/Experimental Use",
    104: "Reserved for Private/Experimental Use",
    105: "Reserved for Private/Experimental Use",
    106: "Reserved for Private/Experimental Use",
    107: "Reserved for Private/Experimental Use",
    108: "Reserved for Private/Experimental Use",
    109: "Reserved for Private/Experimental Use",
    110: "Reserved for Private/Experimental Use",
}

SYMMETRIC_KEY_ALGORITHMS = {
    0: "Plaintext or unencrypted",
    1: "IDEA",
    2: "TripleDES",
    3: "CAST5",
    4: "Blowfish",
    7: "AES-128",
    8: "AES-192",
    9: "AES-256",
    10: "Twofish",
    5: "Reserved",
    6: "Reserved",
    100: "Reserved for Private/Experimental Use",
    101: "Reserved for Private/Experimental Use",
    102: "Reserved for Private/Experimental Use",
    103: "Reserved for Private/Experimental Use",
    104: "Reserved for Private/Experimental Use",
    105: "Reserved for Private/Experimental Use",
    106: "Reserved for Private/Experimental Use",
    107: "Reserved for Private/Experimental Use",
    108: "Reserved for Private/Experimental Use",
    109: "Reserved for Private/Experimental Use",
    110: "Reserved for Private/Experimental Use",
}